from django.db import models
import choices

ADJUSTMENT_FACTOR = 1.015675 # Adjustment factor for dollar amounts, this is for 2006

class State(models.Model):
    code = models.IntegerField()
    name = models.CharField(max_length=80)
    abbreviation = models.CharField(max_length=2)
    
class PUMA(models.Model):
    code = models.IntegerField()
    state = models.ForeignKey(State)

class House(models.Model):
    SERIALNO = models.IntegerField(verbose_name='Housing unit/GQ person serial number')
    DIVISION = models.IntegerField(verbose_name='Division code', choices=choices.DIVISION)
    PUMA = models.IntegerField(verbose_name='Public use microdata area code (PUMA) Designates area of 100,000 or more population. Use with ST for unique code. 00100..08200')
    REGION = models.IntegerField(verbose_name='Region code', choices=choices.REGION)
    ST = models.IntegerField(verbose_name='State Code', choices=choices.ST)
    ADJUST = models.IntegerField(verbose_name='Adjustment factor for dollar amounts (6 implied decimal places)', choices=choices.ADJUST)
    WGTP = models.IntegerField(verbose_name='Housing Weight', choices=choices.WGTP)
    NP = models.IntegerField(verbose_name='Number of person records following this housing record', choices=choices.NP)
    TYPE = models.IntegerField(verbose_name='Type of unit', choices=choices.TYPE)
    ACR = models.IntegerField(verbose_name='Lot size', choices=choices.ACR)
    AGS = models.IntegerField(verbose_name='Sales of Agriculture Products', choices=choices.AGS)
    BDS = models.IntegerField(verbose_name='Bedrooms', choices=choices.BDS)
    BLD = models.IntegerField(verbose_name='Units in structure', choices=choices.BLD)
    BUS = models.IntegerField(verbose_name='Business or medical office on property', choices=choices.BUS)
    CONP = models.IntegerField(verbose_name='Condo fee (monthly amount)', choices=choices.CONP)
    ELEP = models.IntegerField(verbose_name='Electricity (monthly cost)', choices=choices.ELEP)
    FS = models.IntegerField(verbose_name='Food stamp amount', choices=choices.FS)
    FULP = models.IntegerField(verbose_name='House heating fuel (yearly cost)', choices=choices.FULP)
    GASP = models.IntegerField(verbose_name='Gas (monthly cost)', choices=choices.GASP)
    HFL = models.IntegerField(verbose_name='House heating fuel', choices=choices.HFL)
    INSP = models.IntegerField(verbose_name='Fire/hazard/flood insurance (yearly amount)', choices=choices.INSP)
    KIT = models.IntegerField(verbose_name='Complete kitchen facilities', choices=choices.KIT)
    MHP = models.IntegerField(verbose_name='Mobile home costs (yearly amount)', choices=choices.MHP)
    MRGI = models.IntegerField(verbose_name='Payment include fire/hazard/flood insurance', choices=choices.MRGI)
    MRGP = models.IntegerField(verbose_name='Mortgage payment (monthly amount)', choices=choices.MRGP)
    MRGT = models.IntegerField(verbose_name='Payment include real estate taxes', choices=choices.MRGT)
    MRGX = models.IntegerField(verbose_name='Mortgage status', choices=choices.MRGX)
    PLM = models.IntegerField(verbose_name='Complete plumbing facilities', choices=choices.PLM)
    RMS = models.IntegerField(verbose_name='Rooms', choices=choices.RMS)
    RNTM = models.IntegerField(verbose_name='Meals included in rent', choices=choices.RNTM)
    RNTP = models.IntegerField(verbose_name='Monthly rent', choices=choices.RNTP)
    SMP = models.IntegerField(verbose_name='Second mortgage payment (monthly amount)', choices=choices.SMP)
    TEL = models.IntegerField(verbose_name='Telephone in Unit', choices=choices.TEL)
    TEN = models.IntegerField(verbose_name='Tenure', choices=choices.TEN)
    VACS = models.IntegerField(verbose_name='Vacancy status', choices=choices.VACS)
    VAL = models.IntegerField(verbose_name='Property value', choices=choices.VAL)
    VEH = models.IntegerField(verbose_name='Vehicles (1 ton or less) available', choices=choices.VEH)
    WATP = models.IntegerField(verbose_name='Water (yearly cost)', choices=choices.WATP)
    YBL = models.IntegerField(verbose_name='When structure first built', choices=choices.YBL)
    FES = models.IntegerField(verbose_name='Family type and employment status', choices=choices.FES)
    FINCP = models.IntegerField(verbose_name='Family income', choices=choices.FINCP)
    FPARC = models.IntegerField(verbose_name='Family presence and age of related children', choices=choices.FPARC)
    GRNTP = models.IntegerField(verbose_name='Gross rent', choices=choices.GRNTP)
    GRPIP = models.IntegerField(verbose_name='Gross rent as a percentage of household income past 12 months', choices=choices.GRPIP)
    HHL = models.IntegerField(verbose_name='Household language', choices=choices.HHL)
    HHT = models.IntegerField(verbose_name='Household/family type', choices=choices.HHT)
    HINCP = models.IntegerField(verbose_name='Household income', choices=choices.HINCP)
    HUGCL = models.IntegerField(verbose_name='Flag to indicate grandchild living in housing unit', choices=choices.HUGCL)
    HUPAC = models.IntegerField(verbose_name='Family presence and age of children', choices=choices.HUPAC)
    HUPAOC = models.IntegerField(verbose_name='HH presence and age of own children', choices=choices.HUPAOC)
    HUPARC = models.IntegerField(verbose_name='HH presence and age of related children', choices=choices.HUPARC)
    LNGI = models.IntegerField(verbose_name='Linguistic isolation', choices=choices.LNGI)
    MV = models.IntegerField(verbose_name='When moved into this house or apartment', choices=choices.MV)
    NOC = models.IntegerField(verbose_name='Number of own children in household (unweighted)', choices=choices.NOC)
    NPF = models.IntegerField(verbose_name='Number of persons in family (unweighted)', choices=choices.NPF)
    NPP = models.IntegerField(verbose_name='Grandparent headed household with no parent present', choices=choices.NPP)
    NR = models.IntegerField(verbose_name='Presence of nonrelative in household', choices=choices.NR)
    NRC = models.IntegerField(verbose_name='Number of related children in household (unweighted)', choices=choices.NRC)
    OCPIP = models.IntegerField(verbose_name='Selected monthly owner costs as a percentage of household income during the past 12 months', choices=choices.OCPIP)
    PARTNER = models.IntegerField(verbose_name='Unmarried partner household', choices=choices.PARTNER)
    PSF = models.IntegerField(verbose_name='Presence of subfamilies in Household', choices=choices.PSF)
    R18 = models.IntegerField(verbose_name='Presence of persons under 18 years in household (unweighted)', choices=choices.R18)
    R60 = models.IntegerField(verbose_name='Presence of persons 60 years and over in household (unweighted)', choices=choices.R60)
    R65 = models.IntegerField(verbose_name='Presence of persons 65 years and over in household (unweighted)', choices=choices.R65)
    RESMODE = models.IntegerField(verbose_name='Response mode', choices=choices.RESMODE)
    SMOCP = models.IntegerField(verbose_name='Selected monthly owner costs', choices=choices.SMOCP)
    SMX = models.IntegerField(verbose_name='Second mortgage or home equity loan status', choices=choices.SMX)
    SRNT = models.IntegerField(verbose_name='Specified rent unit', choices=choices.SRNT)
    SVAL = models.IntegerField(verbose_name='Specified value unit', choices=choices.SVAL)
    TAXP = models.IntegerField(verbose_name='Property taxes (yearly amount)', choices=choices.TAXP)
    WIF = models.IntegerField(verbose_name='Workers in family during the past 12 months', choices=choices.WIF)
    WKEXREL = models.IntegerField(verbose_name='Work experience of householder and spouse', choices=choices.WKEXREL)
    WORKSTAT = models.IntegerField(verbose_name='Work status of householder or spouse in family households', choices=choices.WORKSTAT)
    FACRP = models.IntegerField(verbose_name='Lot size allocation', choices=choices.FACRP)
    FAGSP = models.IntegerField(verbose_name='Sales of Agricultural Products allocation', choices=choices.FAGSP)
    FBDSP = models.IntegerField(verbose_name='Number of bedrooms allocation', choices=choices.FBDSP)
    FBLDP = models.IntegerField(verbose_name='Units in structure allocation', choices=choices.FBLDP)
    FBUSP = models.IntegerField(verbose_name='Business or medical office on property allocation', choices=choices.FBUSP)
    FCONP = models.IntegerField(verbose_name='Condominium fee allocation', choices=choices.FCONP)
    FELEP = models.IntegerField(verbose_name='Electricity (monthly cost) allocation', choices=choices.FELEP)
    FFSP = models.IntegerField(verbose_name='Food stamp amount (yearly amount) allocation', choices=choices.FFSP)
    FFULP = models.IntegerField(verbose_name='House heating fuel (yearly cost) allocation', choices=choices.FFULP)
    FGASP = models.IntegerField(verbose_name='Gas (monthly cost) allocation', choices=choices.FGASP)
    FHFLP = models.IntegerField(verbose_name='House heating fuel allocation', choices=choices.FHFLP)
    FINSP = models.IntegerField(verbose_name='Fire, hazard, flood insurance allocation', choices=choices.FINSP)
    FKITP = models.IntegerField(verbose_name='Complete kitchen facilities allocation', choices=choices.FKITP)
    FMHP = models.IntegerField(verbose_name='Mobile home costs allocation', choices=choices.FMHP)
    FMRGIP = models.IntegerField(verbose_name='Payment include fire, hazard, flood insurance allocation', choices=choices.FMRGIP)
    FMRGP = models.IntegerField(verbose_name='Regular mortgage payment allocation', choices=choices.FMRGP)
    FMRGTP = models.IntegerField(verbose_name='Payment include real estate taxes allocation', choices=choices.FMRGTP)
    FMRGXP = models.IntegerField(verbose_name='Mortgage status allocation', choices=choices.FMRGXP)
    FMVYP = models.IntegerField(verbose_name='When moved into this house or apartment allocation', choices=choices.FMVYP)
    FPLMP = models.IntegerField(verbose_name='Complete plumbing facilities allocation', choices=choices.FPLMP)
    FRMSP = models.IntegerField(verbose_name='Rooms allocation', choices=choices.FRMSP)
    FRNTMP = models.IntegerField(verbose_name='Meals included in rent allocation', choices=choices.FRNTMP)
    FRNTP = models.IntegerField(verbose_name='Monthly rent allocation', choices=choices.FRNTP)
    FSMP = models.IntegerField(verbose_name='Second mortgage payment allocation', choices=choices.FSMP)
    FSMXHP = models.IntegerField(verbose_name='Home equity loan status allocation', choices=choices.FSMXHP)
    FSMXSP = models.IntegerField(verbose_name='Second mortgage status allocation', choices=choices.FSMXSP)
    FTAXP = models.IntegerField(verbose_name='Taxes on property allocation', choices=choices.FTAXP)
    FTELP = models.IntegerField(verbose_name='Telephones in house allocation', choices=choices.FTELP)
    FTENP = models.IntegerField(verbose_name='Tenure allocation', choices=choices.FTENP)
    FVACSP = models.IntegerField(verbose_name='Vacancy status allocation', choices=choices.FVACSP)
    FVALP = models.IntegerField(verbose_name='Value allocation', choices=choices.FVALP)
    FVEHP = models.IntegerField(verbose_name='Vehicles available by household allocation', choices=choices.FVEHP)
    FWATP = models.IntegerField(verbose_name='Water (yearly cost) allocation', choices=choices.FWATP)
    FYBLP = models.IntegerField(verbose_name='When structure first built allocation', choices=choices.FYBLP)
    WGTP1 = models.IntegerField(verbose_name='Housing Weight replicate 1', choices=choices.WGTP1)
    WGTP2 = models.IntegerField(verbose_name='Housing Weight replicate 2', choices=choices.WGTP2)
    WGTP3 = models.IntegerField(verbose_name='Housing Weight replicate 3', choices=choices.WGTP3)
    WGTP4 = models.IntegerField(verbose_name='Housing Weight replicate 4', choices=choices.WGTP4)
    WGTP5 = models.IntegerField(verbose_name='Housing Weight replicate 5', choices=choices.WGTP5)
    WGTP6 = models.IntegerField(verbose_name='Housing Weight replicate 6', choices=choices.WGTP6)
    WGTP7 = models.IntegerField(verbose_name='Housing Weight replicate 7', choices=choices.WGTP7)
    WGTP8 = models.IntegerField(verbose_name='Housing Weight replicate 8', choices=choices.WGTP8)
    WGTP9 = models.IntegerField(verbose_name='Housing Weight replicate 9', choices=choices.WGTP9)
    WGTP10 = models.IntegerField(verbose_name='Housing Weight replicate 10', choices=choices.WGTP10)
    WGTP11 = models.IntegerField(verbose_name='Housing Weight replicate 11', choices=choices.WGTP11)
    WGTP12 = models.IntegerField(verbose_name='Housing Weight replicate 12', choices=choices.WGTP12)
    WGTP13 = models.IntegerField(verbose_name='Housing Weight replicate 13', choices=choices.WGTP13)
    WGTP14 = models.IntegerField(verbose_name='Housing Weight replicate 14', choices=choices.WGTP14)
    WGTP15 = models.IntegerField(verbose_name='Housing Weight replicate 15', choices=choices.WGTP15)
    WGTP16 = models.IntegerField(verbose_name='Housing Weight replicate 16', choices=choices.WGTP16)
    WGTP17 = models.IntegerField(verbose_name='Housing Weight replicate 17', choices=choices.WGTP17)
    WGTP18 = models.IntegerField(verbose_name='Housing Weight replicate 18', choices=choices.WGTP18)
    WGTP19 = models.IntegerField(verbose_name='Housing Weight replicate 19', choices=choices.WGTP19)
    WGTP20 = models.IntegerField(verbose_name='Housing Weight replicate 20', choices=choices.WGTP20)
    WGTP21 = models.IntegerField(verbose_name='Housing Weight replicate 21', choices=choices.WGTP21)
    WGTP22 = models.IntegerField(verbose_name='Housing Weight replicate 22', choices=choices.WGTP22)
    WGTP23 = models.IntegerField(verbose_name='Housing Weight replicate 23', choices=choices.WGTP23)
    WGTP24 = models.IntegerField(verbose_name='Housing Weight replicate 24', choices=choices.WGTP24)
    WGTP25 = models.IntegerField(verbose_name='Housing Weight replicate 25', choices=choices.WGTP25)
    WGTP26 = models.IntegerField(verbose_name='Housing Weight replicate 26', choices=choices.WGTP26)
    WGTP27 = models.IntegerField(verbose_name='Housing Weight replicate 27', choices=choices.WGTP27)
    WGTP28 = models.IntegerField(verbose_name='Housing Weight replicate 28', choices=choices.WGTP28)
    WGTP29 = models.IntegerField(verbose_name='Housing Weight replicate 29', choices=choices.WGTP29)
    WGTP30 = models.IntegerField(verbose_name='Housing Weight replicate 30', choices=choices.WGTP30)
    WGTP31 = models.IntegerField(verbose_name='Housing Weight replicate 31', choices=choices.WGTP31)
    WGTP32 = models.IntegerField(verbose_name='Housing Weight replicate 32', choices=choices.WGTP32)
    WGTP33 = models.IntegerField(verbose_name='Housing Weight replicate 33', choices=choices.WGTP33)
    WGTP34 = models.IntegerField(verbose_name='Housing Weight replicate 34', choices=choices.WGTP34)
    WGTP35 = models.IntegerField(verbose_name='Housing Weight replicate 35', choices=choices.WGTP35)
    WGTP36 = models.IntegerField(verbose_name='Housing Weight replicate 36', choices=choices.WGTP36)
    WGTP37 = models.IntegerField(verbose_name='Housing Weight replicate 37', choices=choices.WGTP37)
    WGTP38 = models.IntegerField(verbose_name='Housing Weight replicate 38', choices=choices.WGTP38)
    WGTP39 = models.IntegerField(verbose_name='Housing Weight replicate 39', choices=choices.WGTP39)
    WGTP40 = models.IntegerField(verbose_name='Housing Weight replicate 40', choices=choices.WGTP40)
    WGTP41 = models.IntegerField(verbose_name='Housing Weight replicate 41', choices=choices.WGTP41)
    WGTP42 = models.IntegerField(verbose_name='Housing Weight replicate 42', choices=choices.WGTP42)
    WGTP43 = models.IntegerField(verbose_name='Housing Weight replicate 43', choices=choices.WGTP43)
    WGTP44 = models.IntegerField(verbose_name='Housing Weight replicate 44', choices=choices.WGTP44)
    WGTP45 = models.IntegerField(verbose_name='Housing Weight replicate 45', choices=choices.WGTP45)
    WGTP46 = models.IntegerField(verbose_name='Housing Weight replicate 46', choices=choices.WGTP46)
    WGTP47 = models.IntegerField(verbose_name='Housing Weight replicate 47', choices=choices.WGTP47)
    WGTP48 = models.IntegerField(verbose_name='Housing Weight replicate 48', choices=choices.WGTP48)
    WGTP49 = models.IntegerField(verbose_name='Housing Weight replicate 49', choices=choices.WGTP49)
    WGTP50 = models.IntegerField(verbose_name='Housing Weight replicate 50', choices=choices.WGTP50)
    WGTP51 = models.IntegerField(verbose_name='Housing Weight replicate 51', choices=choices.WGTP51)
    WGTP52 = models.IntegerField(verbose_name='Housing Weight replicate 52', choices=choices.WGTP52)
    WGTP53 = models.IntegerField(verbose_name='Housing Weight replicate 53', choices=choices.WGTP53)
    WGTP54 = models.IntegerField(verbose_name='Housing Weight replicate 54', choices=choices.WGTP54)
    WGTP55 = models.IntegerField(verbose_name='Housing Weight replicate 55', choices=choices.WGTP55)
    WGTP56 = models.IntegerField(verbose_name='Housing Weight replicate 56', choices=choices.WGTP56)
    WGTP57 = models.IntegerField(verbose_name='Housing Weight replicate 57', choices=choices.WGTP57)
    WGTP58 = models.IntegerField(verbose_name='Housing Weight replicate 58', choices=choices.WGTP58)
    WGTP59 = models.IntegerField(verbose_name='Housing Weight replicate 59', choices=choices.WGTP59)
    WGTP60 = models.IntegerField(verbose_name='Housing Weight replicate 60', choices=choices.WGTP60)
    WGTP61 = models.IntegerField(verbose_name='Housing Weight replicate 61', choices=choices.WGTP61)
    WGTP62 = models.IntegerField(verbose_name='Housing Weight replicate 62', choices=choices.WGTP62)
    WGTP63 = models.IntegerField(verbose_name='Housing Weight replicate 63', choices=choices.WGTP63)
    WGTP64 = models.IntegerField(verbose_name='Housing Weight replicate 64', choices=choices.WGTP64)
    WGTP65 = models.IntegerField(verbose_name='Housing Weight replicate 65', choices=choices.WGTP65)
    WGTP66 = models.IntegerField(verbose_name='Housing Weight replicate 66', choices=choices.WGTP66)
    WGTP67 = models.IntegerField(verbose_name='Housing Weight replicate 67', choices=choices.WGTP67)
    WGTP68 = models.IntegerField(verbose_name='Housing Weight replicate 68', choices=choices.WGTP68)
    WGTP69 = models.IntegerField(verbose_name='Housing Weight replicate 69', choices=choices.WGTP69)
    WGTP70 = models.IntegerField(verbose_name='Housing Weight replicate 70', choices=choices.WGTP70)
    WGTP71 = models.IntegerField(verbose_name='Housing Weight replicate 71', choices=choices.WGTP71)
    WGTP72 = models.IntegerField(verbose_name='Housing Weight replicate 72', choices=choices.WGTP72)
    WGTP73 = models.IntegerField(verbose_name='Housing Weight replicate 73', choices=choices.WGTP73)
    WGTP74 = models.IntegerField(verbose_name='Housing Weight replicate 74', choices=choices.WGTP74)
    WGTP75 = models.IntegerField(verbose_name='Housing Weight replicate 75', choices=choices.WGTP75)
    WGTP76 = models.IntegerField(verbose_name='Housing Weight replicate 76', choices=choices.WGTP76)
    WGTP77 = models.IntegerField(verbose_name='Housing Weight replicate 77', choices=choices.WGTP77)
    WGTP78 = models.IntegerField(verbose_name='Housing Weight replicate 78', choices=choices.WGTP78)
    WGTP79 = models.IntegerField(verbose_name='Housing Weight replicate 79', choices=choices.WGTP79)

class Person(models.Model):
    RT = models.IntegerField(verbose_name='Record Type', choices=choices.RT)
    SERIALNO = models.IntegerField(verbose_name='Housing unit/GQ person serial number', choices=choices.SERIALNO)
    SPORDER = models.IntegerField(verbose_name='Person number', choices=choices.SPORDER)
    PUMA = models.IntegerField(verbose_name='Public use microdata area code (PUMA) Designates area of 100,000 or more population. Use with ST for unique code. 00100..08200', choices=choices.PUMA)
    ST = models.IntegerField(verbose_name='State Code', choices=choices.ST)
    ADJUST = models.IntegerField(verbose_name='Adjustment factor for dollar amounts (6 implied decimal places)', choices=choices.ADJUST)
    PWGTP = models.IntegerField(verbose_name='Person\'s weight', choices=choices.PWGTP)
    AGEP = models.IntegerField(verbose_name='Age', choices=choices.AGEP)
    CIT = models.IntegerField(verbose_name='Citizenship status', choices=choices.CIT)
    COW = models.IntegerField(verbose_name='Class of worker', choices=choices.COW)
    DDRS = models.IntegerField(verbose_name='Difficulty dressing', choices=choices.DDRS)
    DEYE = models.IntegerField(verbose_name='Vision or hearing difficulty', choices=choices.DEYE)
    DOUT = models.IntegerField(verbose_name='Difficulty going out', choices=choices.DOUT)
    DPHY = models.IntegerField(verbose_name='Physical difficulty', choices=choices.DPHY)
    DREM = models.IntegerField(verbose_name='Difficulty remembering', choices=choices.DREM)
    DWRK = models.IntegerField(verbose_name='Difficulty working', choices=choices.DWRK)
    ENG = models.IntegerField(verbose_name='Ability to speak English', choices=choices.ENG)
    FER = models.IntegerField(verbose_name='Child born within the past 12 months', choices=choices.FER)
    GCL = models.IntegerField(verbose_name='Grandchildren living in this house', choices=choices.GCL)
    GCM = models.IntegerField(verbose_name='Months responsible for grandchildren', choices=choices.GCM)
    GCR = models.IntegerField(verbose_name='Responsible for grandchildren house/institutional GQ)', choices=choices.GCR)
    INTP = models.IntegerField(verbose_name='Interest, dividends, and net rental income past 12 months (signed)', choices=choices.INTP)
    JWMNP = models.IntegerField(verbose_name='Travel time to work', choices=choices.JWMNP)
    JWRIP = models.IntegerField(verbose_name='Vehicle occupancy', choices=choices.JWRIP)
    JWTR = models.IntegerField(verbose_name='Means of transportation to work', choices=choices.JWTR)
    LANX = models.IntegerField(verbose_name='Language other than English at home', choices=choices.LANX)
    MAR = models.IntegerField(verbose_name='Marital status', choices=choices.MAR)
    MIG = models.IntegerField(verbose_name='Mobility status (lived here 1 year ago)', choices=choices.MIG)
    MIL = models.IntegerField(verbose_name='Military service', choices=choices.MIL)
    MILY = models.IntegerField(verbose_name='Years of active duty military service', choices=choices.MILY)
    MLPA = models.IntegerField(verbose_name='Served September 2001 or later', choices=choices.MLPA)
    MLPB = models.IntegerField(verbose_name='Served August 1990 - August 2001 (including Persian Gulf War)', choices=choices.MLPB)
    MLPC = models.IntegerField(verbose_name='Served September 1980 - July 1990', choices=choices.MLPC)
    MLPD = models.IntegerField(verbose_name='Served May 1975 - August 1980', choices=choices.MLPD)
    MLPE = models.IntegerField(verbose_name='Served Vietnam era (August 1964 - April 1975)', choices=choices.MLPE)
    MLPF = models.IntegerField(verbose_name='Served March 1961 - July 1964', choices=choices.MLPF)
    MLPG = models.IntegerField(verbose_name='Served February 1955 - February 1961', choices=choices.MLPG)
    MLPH = models.IntegerField(verbose_name='Served Korean War (July 1950 - January 1955)', choices=choices.MLPH)
    MLPI = models.IntegerField(verbose_name='Served January 1947 - June 1950', choices=choices.MLPI)
    MLPJ = models.IntegerField(verbose_name='Served World War II (December 1941 - December 1946)', choices=choices.MLPJ)
    MLPK = models.IntegerField(verbose_name='Served November 1941 or earlier', choices=choices.MLPK)
    NWAB = models.IntegerField(verbose_name='Temporary absence from work', choices=choices.NWAB)
    NWAV = models.IntegerField(verbose_name='Available for work', choices=choices.NWAV)
    NWLA = models.IntegerField(verbose_name='On layoff from work', choices=choices.NWLA)
    NWLK = models.IntegerField(verbose_name='Looking for work', choices=choices.NWLK)
    NWRE = models.IntegerField(verbose_name='Informed of recall', choices=choices.NWRE)
    OIP = models.IntegerField(verbose_name='All other income past 12 months', choices=choices.OIP)
    PAP = models.IntegerField(verbose_name='Public assistance income past 12 months', choices=choices.PAP)
    REL = models.IntegerField(verbose_name='Relationship', choices=choices.REL)
    RETP = models.IntegerField(verbose_name='Retirement income past 12 months', choices=choices.RETP)
    SCH = models.IntegerField(verbose_name='School enrollment', choices=choices.SCH)
    SCHG = models.IntegerField(verbose_name='Grade level attending', choices=choices.SCHG)
    SCHL = models.IntegerField(verbose_name='Educational attainment', choices=choices.SCHL)
    SEMP = models.IntegerField(verbose_name='Self-employment income past 12 months (signed)', choices=choices.SEMP)
    SEX = models.IntegerField(verbose_name='Sex', choices=choices.SEX)
    SSIP = models.IntegerField(verbose_name='Supplementary Security Income past 12 months', choices=choices.SSIP)
    SSP = models.IntegerField(verbose_name='Social security income past 12 months', choices=choices.SSP)
    WAGP = models.IntegerField(verbose_name='Wages or salary income past 12 months', choices=choices.WAGP)
    WKHP = models.IntegerField(verbose_name='Usual hours worked per week past 12 months', choices=choices.WKHP)
    WKL = models.IntegerField(verbose_name='When last worked', choices=choices.WKL)
    WKW = models.IntegerField(verbose_name='Weeks worked past 12 months', choices=choices.WKW)
    YOEP = models.IntegerField(verbose_name='Year of entry', choices=choices.YOEP)
    UWRK = models.IntegerField(verbose_name='Worked last week', choices=choices.UWRK)
    ANC = models.IntegerField(verbose_name='Ancestry recode', choices=choices.ANC)
    ANC1P = models.IntegerField(verbose_name='Recoded Detailed Ancestry - first entry', choices=choices.ANC1P)
    ANC2P = models.IntegerField(verbose_name='Recoded Detailed Ancestry - second entry', choices=choices.ANC2P)
    DECADE = models.IntegerField(verbose_name='Decade of entry', choices=choices.DECADE)
    DRIVESP = models.IntegerField(verbose_name='Number of vehicles calculated from JWRI', choices=choices.DRIVESP)
    DS = models.IntegerField(verbose_name='Disability recode', choices=choices.DS)
    ESP = models.IntegerField(verbose_name='Employment status of parents', choices=choices.ESP)
    ESR = models.IntegerField(verbose_name='Employment status recode', choices=choices.ESR)
    HISP = models.IntegerField(verbose_name='Recoded detailed Hispanic origin', choices=choices.HISP)
    INDP = models.IntegerField(verbose_name='Industry recode', choices=choices.INDP)
    JWAP = models.IntegerField(verbose_name='Time of arrival at work - hour and minute', choices=choices.JWAP)
    JWDP = models.IntegerField(verbose_name='Time of departure for work - hour and minute', choices=choices.JWDP)
    LANP = models.IntegerField(verbose_name='Language spoken at home', choices=choices.LANP)
    MIGPUMA = models.IntegerField(verbose_name='Migration PUMA', choices=choices.MIGPUMA)
    MIGSP = models.IntegerField(verbose_name='Migration recode - State or foreign country code', choices=choices.MIGSP)
    MSP = models.IntegerField(verbose_name='Married, spouse present/spouse absent', choices=choices.MSP)
    NAICSP = models.CharField(verbose_name='NAICS Industry code', max_length=8, choices=choices.NAICSP)
    NATIVITY = models.IntegerField(verbose_name='Nativity', choices=choices.NATIVITY)
    NOP = models.IntegerField(verbose_name='Nativity of parent', choices=choices.NOP)
    OC = models.IntegerField(verbose_name='Own child', choices=choices.OC)
    OCCP = models.IntegerField(verbose_name='Occupation recode', choices=choices.OCCP)
    PAOC = models.IntegerField(verbose_name='Presence and age of own children', choices=choices.PAOC)
    PERNP = models.IntegerField(verbose_name='Total person\'s earnings', choices=choices.PERNP)
    PINCP = models.IntegerField(verbose_name='Total person\'s income (signed)', choices=choices.PINCP)
    POBP = models.IntegerField(verbose_name='Place of birth (Recode)', choices=choices.POBP)
    POVPIP = models.IntegerField(verbose_name='Person poverty status recode', choices=choices.POVPIP)
    POWPUMA = models.IntegerField(verbose_name='Place of work PUMA', choices=choices.POWPUMA)
    POWSP = models.IntegerField(verbose_name='Place of work - State or foreign country recode', choices=choices.POWSP)
    QTRBIR = models.IntegerField(verbose_name='Quarter of birth', choices=choices.QTRBIR)
    RAC1P = models.IntegerField(verbose_name='Recoded detailed race code', choices=choices.RAC1P)
    RAC2P = models.IntegerField(verbose_name='Recoded detailed race code', choices=choices.RAC2P)
    RAC3P = models.IntegerField(verbose_name='Recoded detailed race code', choices=choices.RAC3P)
    RACAIAN = models.IntegerField(verbose_name='American Indian and Alaska Native recode (American Indian and Alaska Native alone or in combination with one or more other races)', choices=choices.RACAIAN)
    RACASN = models.IntegerField(verbose_name='Asian recode (Asian alone or in combination with one or more other races)', choices=choices.RACASN)
    RACBLK = models.IntegerField(verbose_name='Black or African American recode (Black alone or in combination with one or more other races)', choices=choices.RACBLK)
    RACNHPI = models.IntegerField(verbose_name='Native Hawaiian and Other Pacific Islander recode (Native Hawaiian and Other Pacific Islander alone or in combination with one or more other races)', choices=choices.RACNHPI)
    RACNUM = models.IntegerField(verbose_name='Number of major race groups represented', choices=choices.RACNUM)
    RACSOR = models.IntegerField(verbose_name='Some other race recode (Some other race alone or in combination with one or more other races)', choices=choices.RACSOR)
    RACWHT = models.IntegerField(verbose_name='White recode (White alone or in combination with one or more other races)', choices=choices.RACWHT)
    RC = models.IntegerField(verbose_name='Related child', choices=choices.RC)
    SFN = models.IntegerField(verbose_name='Subfamily number', choices=choices.SFN)
    SFR = models.IntegerField(verbose_name='Subfamily relationship', choices=choices.SFR)
    SOCP = models.CharField(verbose_name='SOC Occupation code', max_length=6, choices=choices.SOCP)
    VPS = models.IntegerField(verbose_name='Veteran period of service', choices=choices.VPS)
    WAOB = models.IntegerField(verbose_name='World area of birth', choices=choices.WAOB)
    FAGEP = models.IntegerField(verbose_name='Age allocation flag', choices=choices.FAGEP)
    FANCP = models.IntegerField(verbose_name='Ancestry allocation flag', choices=choices.FANCP)
    FCITP = models.IntegerField(verbose_name='Citizenship allocation flag', choices=choices.FCITP)
    FCOWP = models.IntegerField(verbose_name='Class of worker allocation flag', choices=choices.FCOWP)
    FDDRSP = models.IntegerField(verbose_name='Difficulty dressing allocation flag', choices=choices.FDDRSP)
    FDEYEP = models.IntegerField(verbose_name='Vision difficulty allocation flag', choices=choices.FDEYEP)
    FDOUTP = models.IntegerField(verbose_name='Difficulty going out allocation flag', choices=choices.FDOUTP)
    FDPHYP = models.IntegerField(verbose_name='Physical difficulty allocation flag', choices=choices.FDPHYP)
    FDREMP = models.IntegerField(verbose_name='Difficulty remembering allocation flag', choices=choices.FDREMP)
    FDWRKP = models.IntegerField(verbose_name='Difficulty working allocation flag', choices=choices.FDWRKP)
    FENGP = models.IntegerField(verbose_name='Ability to speak English allocation flag', choices=choices.FENGP)
    FESRP = models.IntegerField(verbose_name='Employment status recode allocation flag', choices=choices.FESRP)
    FFERP = models.IntegerField(verbose_name='Children born within the past 12 months allocation flag', choices=choices.FFERP)
    FGCLP = models.IntegerField(verbose_name='Grandchildren living in house allocation flag', choices=choices.FGCLP)
    FGCMP = models.IntegerField(verbose_name='Months responsible for grandchildren allocation flag', choices=choices.FGCMP)
    FGCRP = models.IntegerField(verbose_name='Responsible for grandchildren allocation flag', choices=choices.FGCRP)
    FHISP = models.IntegerField(verbose_name='Detailed Hispanic origin allocation flag', choices=choices.FHISP)
    FINDP = models.IntegerField(verbose_name='Industry allocation flag', choices=choices.FINDP)
    FINTP = models.IntegerField(verbose_name='Interest, dividend, and net rental income allocation flag', choices=choices.FINTP)
    FJWDP = models.IntegerField(verbose_name='Time of departure to work allocation flag', choices=choices.FJWDP)
    FJWMNP = models.IntegerField(verbose_name='Travel time to work allocation flag', choices=choices.FJWMNP)
    FJWRIP = models.IntegerField(verbose_name='Vehicle occupancy allocation flag', choices=choices.FJWRIP)
    FJWTRP = models.IntegerField(verbose_name='Means of transportation to work allocation flag', choices=choices.FJWTRP)
    FLANP = models.IntegerField(verbose_name='Language spoken at home allocation flag', choices=choices.FLANP)
    FLANXP = models.IntegerField(verbose_name='Language other than English allocation flag', choices=choices.FLANXP)
    FMARP = models.IntegerField(verbose_name='Marital status allocation flag', choices=choices.FMARP)
    FMIGP = models.IntegerField(verbose_name='Mobility status allocation flag', choices=choices.FMIGP)
    FMIGSP = models.IntegerField(verbose_name='Migration state allocation flag', choices=choices.FMIGSP)
    FMILPP = models.IntegerField(verbose_name='Military periods of service allocation flag', choices=choices.FMILPP)
    FMILSP = models.IntegerField(verbose_name='Military service allocation flag', choices=choices.FMILSP)
    FMILYP = models.IntegerField(verbose_name='Years of military service allocation flag', choices=choices.FMILYP)
    FOCCP = models.IntegerField(verbose_name='Occupation allocation flag', choices=choices.FOCCP)
    FOIP = models.IntegerField(verbose_name='All other income allocation flag', choices=choices.FOIP)
    FPAP = models.IntegerField(verbose_name='Public assistance income allocation flag', choices=choices.FPAP)
    FPOBP = models.IntegerField(verbose_name='Place of birth allocatin flag', choices=choices.FPOBP)
    FPOWSP = models.IntegerField(verbose_name='Place of work state allocation flag', choices=choices.FPOWSP)
    FRACP = models.IntegerField(verbose_name='Detailed race allocation flag', choices=choices.FRACP)
    FRELP = models.IntegerField(verbose_name='Relationship allocation flag', choices=choices.FRELP)
    FRETP = models.IntegerField(verbose_name='Retirement income allocation flag', choices=choices.FRETP)
    FSCHGP = models.IntegerField(verbose_name='Grade attending allocation flag', choices=choices.FSCHGP)
    FSCHLP = models.IntegerField(verbose_name='Highest education allocation flag', choices=choices.FSCHLP)
    FSCHP = models.IntegerField(verbose_name='School enrollment allocation flag', choices=choices.FSCHP)
    FSEMP = models.IntegerField(verbose_name='Self-employment income allocation flag', choices=choices.FSEMP)
    FSEXP = models.IntegerField(verbose_name='Sex allocation flag', choices=choices.FSEXP)
    FSSIP = models.IntegerField(verbose_name='Supplementary Security Income allocation flag', choices=choices.FSSIP)
    FSSP = models.IntegerField(verbose_name='Social Security income allocation flag', choices=choices.FSSP)
    FWAGP = models.IntegerField(verbose_name='Wages and salary income allocation flag', choices=choices.FWAGP)
    FWKHP = models.IntegerField(verbose_name='Usual hours worked per week past 12 months allocation flag', choices=choices.FWKHP)
    FWKLP = models.IntegerField(verbose_name='Last worked allocation flag', choices=choices.FWKLP)
    FWKWP = models.IntegerField(verbose_name='Weeks worked past 12 months allocation flag', choices=choices.FWKWP)
    FYOEP = models.IntegerField(verbose_name='Year of entry allocation flag', choices=choices.FYOEP)
    PWGTP1 = models.IntegerField(verbose_name='Person\'s Weight replicate 1', choices=choices.PWGTP1)
    PWGTP2 = models.IntegerField(verbose_name='Person\'s Weight replicate 2', choices=choices.PWGTP2)
    PWGTP3 = models.IntegerField(verbose_name='Person\'s Weight replicate 3', choices=choices.PWGTP3)
    PWGTP4 = models.IntegerField(verbose_name='Person\'s Weight replicate 4', choices=choices.PWGTP4)
    PWGTP5 = models.IntegerField(verbose_name='Person\'s Weight replicate 5', choices=choices.PWGTP5)
    PWGTP6 = models.IntegerField(verbose_name='Person\'s Weight replicate 6', choices=choices.PWGTP6)
    PWGTP7 = models.IntegerField(verbose_name='Person\'s Weight replicate 7', choices=choices.PWGTP7)
    PWGTP8 = models.IntegerField(verbose_name='Person\'s Weight replicate 8', choices=choices.PWGTP8)
    PWGTP9 = models.IntegerField(verbose_name='Person\'s Weight replicate 9', choices=choices.PWGTP9)
    PWGTP10 = models.IntegerField(verbose_name='Person\'s Weight replicate 10', choices=choices.PWGTP10)
    PWGTP11 = models.IntegerField(verbose_name='Person\'s Weight replicate 11', choices=choices.PWGTP11)
    PWGTP12 = models.IntegerField(verbose_name='Person\'s Weight replicate 12', choices=choices.PWGTP12)
    PWGTP13 = models.IntegerField(verbose_name='Person\'s Weight replicate 13', choices=choices.PWGTP13)
    PWGTP14 = models.IntegerField(verbose_name='Person\'s Weight replicate 14', choices=choices.PWGTP14)
    PWGTP15 = models.IntegerField(verbose_name='Person\'s Weight replicate 15', choices=choices.PWGTP15)
    PWGTP16 = models.IntegerField(verbose_name='Person\'s Weight replicate 16', choices=choices.PWGTP16)
    PWGTP17 = models.IntegerField(verbose_name='Person\'s Weight replicate 17', choices=choices.PWGTP17)
    PWGTP18 = models.IntegerField(verbose_name='Person\'s Weight replicate 18', choices=choices.PWGTP18)
    PWGTP19 = models.IntegerField(verbose_name='Person\'s Weight replicate 19', choices=choices.PWGTP19)
    PWGTP20 = models.IntegerField(verbose_name='Person\'s Weight replicate 20', choices=choices.PWGTP20)
    PWGTP21 = models.IntegerField(verbose_name='Person\'s Weight replicate 21', choices=choices.PWGTP21)
    PWGTP22 = models.IntegerField(verbose_name='Person\'s Weight replicate 22', choices=choices.PWGTP22)
    PWGTP23 = models.IntegerField(verbose_name='Person\'s Weight replicate 23', choices=choices.PWGTP23)
    PWGTP24 = models.IntegerField(verbose_name='Person\'s Weight replicate 24', choices=choices.PWGTP24)
    PWGTP25 = models.IntegerField(verbose_name='Person\'s Weight replicate 25', choices=choices.PWGTP25)
    PWGTP26 = models.IntegerField(verbose_name='Person\'s Weight replicate 26', choices=choices.PWGTP26)
    PWGTP27 = models.IntegerField(verbose_name='Person\'s Weight replicate 27', choices=choices.PWGTP27)
    PWGTP28 = models.IntegerField(verbose_name='Person\'s Weight replicate 28', choices=choices.PWGTP28)
    PWGTP29 = models.IntegerField(verbose_name='Person\'s Weight replicate 29', choices=choices.PWGTP29)
    PWGTP30 = models.IntegerField(verbose_name='Person\'s Weight replicate 30', choices=choices.PWGTP30)
    PWGTP31 = models.IntegerField(verbose_name='Person\'s Weight replicate 31', choices=choices.PWGTP31)
    PWGTP32 = models.IntegerField(verbose_name='Person\'s Weight replicate 32', choices=choices.PWGTP32)
    PWGTP33 = models.IntegerField(verbose_name='Person\'s Weight replicate 33', choices=choices.PWGTP33)
    PWGTP34 = models.IntegerField(verbose_name='Person\'s Weight replicate 34', choices=choices.PWGTP34)
    PWGTP35 = models.IntegerField(verbose_name='Person\'s Weight replicate 35', choices=choices.PWGTP35)
    PWGTP36 = models.IntegerField(verbose_name='Person\'s Weight replicate 36', choices=choices.PWGTP36)
    PWGTP37 = models.IntegerField(verbose_name='Person\'s Weight replicate 37', choices=choices.PWGTP37)
    PWGTP38 = models.IntegerField(verbose_name='Person\'s Weight replicate 38', choices=choices.PWGTP38)
    PWGTP39 = models.IntegerField(verbose_name='Person\'s Weight replicate 39', choices=choices.PWGTP39)
    PWGTP40 = models.IntegerField(verbose_name='Person\'s Weight replicate 40', choices=choices.PWGTP40)
    PWGTP41 = models.IntegerField(verbose_name='Person\'s Weight replicate 41', choices=choices.PWGTP41)
    PWGTP42 = models.IntegerField(verbose_name='Person\'s Weight replicate 42', choices=choices.PWGTP42)
    PWGTP43 = models.IntegerField(verbose_name='Person\'s Weight replicate 43', choices=choices.PWGTP43)
    PWGTP44 = models.IntegerField(verbose_name='Person\'s Weight replicate 44', choices=choices.PWGTP44)
    PWGTP45 = models.IntegerField(verbose_name='Person\'s Weight replicate 45', choices=choices.PWGTP45)
    PWGTP46 = models.IntegerField(verbose_name='Person\'s Weight replicate 46', choices=choices.PWGTP46)
    PWGTP47 = models.IntegerField(verbose_name='Person\'s Weight replicate 47', choices=choices.PWGTP47)
    PWGTP48 = models.IntegerField(verbose_name='Person\'s Weight replicate 48', choices=choices.PWGTP48)
    PWGTP49 = models.IntegerField(verbose_name='Person\'s Weight replicate 49', choices=choices.PWGTP49)
    PWGTP50 = models.IntegerField(verbose_name='Person\'s Weight replicate 50', choices=choices.PWGTP50)
    PWGTP51 = models.IntegerField(verbose_name='Person\'s Weight replicate 51', choices=choices.PWGTP51)
    PWGTP52 = models.IntegerField(verbose_name='Person\'s Weight replicate 52', choices=choices.PWGTP52)
    PWGTP53 = models.IntegerField(verbose_name='Person\'s Weight replicate 53', choices=choices.PWGTP53)
    PWGTP54 = models.IntegerField(verbose_name='Person\'s Weight replicate 54', choices=choices.PWGTP54)
    PWGTP55 = models.IntegerField(verbose_name='Person\'s Weight replicate 55', choices=choices.PWGTP55)
    PWGTP56 = models.IntegerField(verbose_name='Person\'s Weight replicate 56', choices=choices.PWGTP56)
    PWGTP57 = models.IntegerField(verbose_name='Person\'s Weight replicate 57', choices=choices.PWGTP57)
    PWGTP58 = models.IntegerField(verbose_name='Person\'s Weight replicate 58', choices=choices.PWGTP58)
    PWGTP59 = models.IntegerField(verbose_name='Person\'s Weight replicate 59', choices=choices.PWGTP59)
    PWGTP60 = models.IntegerField(verbose_name='Person\'s Weight replicate 60', choices=choices.PWGTP60)
    PWGTP61 = models.IntegerField(verbose_name='Person\'s Weight replicate 61', choices=choices.PWGTP61)
    PWGTP62 = models.IntegerField(verbose_name='Person\'s Weight replicate 62', choices=choices.PWGTP62)
    PWGTP63 = models.IntegerField(verbose_name='Person\'s Weight replicate 63', choices=choices.PWGTP63)
    PWGTP64 = models.IntegerField(verbose_name='Person\'s Weight replicate 64', choices=choices.PWGTP64)
    PWGTP65 = models.IntegerField(verbose_name='Person\'s Weight replicate 65', choices=choices.PWGTP65)
    PWGTP66 = models.IntegerField(verbose_name='Person\'s Weight replicate 66', choices=choices.PWGTP66)
    PWGTP67 = models.IntegerField(verbose_name='Person\'s Weight replicate 67', choices=choices.PWGTP67)
    PWGTP68 = models.IntegerField(verbose_name='Person\'s Weight replicate 68', choices=choices.PWGTP68)
    PWGTP69 = models.IntegerField(verbose_name='Person\'s Weight replicate 69', choices=choices.PWGTP69)
    PWGTP70 = models.IntegerField(verbose_name='Person\'s Weight replicate 70', choices=choices.PWGTP70)
    PWGTP71 = models.IntegerField(verbose_name='Person\'s Weight replicate 71', choices=choices.PWGTP71)
    PWGTP72 = models.IntegerField(verbose_name='Person\'s Weight replicate 72', choices=choices.PWGTP72)
    PWGTP73 = models.IntegerField(verbose_name='Person\'s Weight replicate 73', choices=choices.PWGTP73)
    PWGTP74 = models.IntegerField(verbose_name='Person\'s Weight replicate 74', choices=choices.PWGTP74)
    PWGTP75 = models.IntegerField(verbose_name='Person\'s Weight replicate 75', choices=choices.PWGTP75)
    PWGTP76 = models.IntegerField(verbose_name='Person\'s Weight replicate 76', choices=choices.PWGTP76)
    PWGTP77 = models.IntegerField(verbose_name='Person\'s Weight replicate 77', choices=choices.PWGTP77)
    PWGTP78 = models.IntegerField(verbose_name='Person\'s Weight replicate 78', choices=choices.PWGTP78)
    PWGTP79 = models.IntegerField(verbose_name='Person\'s Weight replicate 79', choices=choices.PWGTP79)

